name: Reusable Flow
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: The name of the deployable artifact files
        required: false
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/dowload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying..."