name: Reusable Flow
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    secrets: 
      some-secret:
        required: true
    outputs:
      result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy }} # only use in reusable flow
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying..."
      - name: Set result output
        run: echo "::set-output name=step-result::success"